language: dart

sudo: false

dart:
  - dev
  - stable

dart_task:
  - test

matrix:
  include:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task:
        dartanalyzer: --fatal-warnings --fatal-hints .
    - dart: stable
      dart_task:
        dartanalyzer: --fatal-warnings .
    - dart: stable
      dart_task: dartfmt

cache:
  directories:
    - $HOME/.pub-cache