name: zip_code_jp
description: A dart package for Japan Post official zip code search and update.
version: 0.0.1
author: Kazuki Yamaguchi <y.kazuki0614n@gmail.com>
homepage: https://github.com/yamarkz/zip_code_jp

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^4.0.3
  yaml: ^2.2.0
  intl: ^0.16.0
  archive: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: